Add just percentage ranking
Banalian/ExtraLeaderboardPositions pull request #17
Opened 2023-06-30 07:14 UTC by tboby

This is basically just a re-application of https://github.com/Banalian/ExtraLeaderboardPositions/pull/8 to use your new API functions but reducing it to the simple first part of just the percentage column without any extra positions.

It adds a single setting "Show percentage column" which can only be ticked when the External API is enabled. This setting forces the total player count to be fetched from the API, then calculates the percentage ranking for every position.

It also slightly adjusts the table rendering to count columns (to avoid the empty column padding on the right).

I might do the extra positions based off % next :)

2023-06-30 07:16 UTC, tboby commented
![image](https://github.com/Banalian/ExtraLeaderboardPositions/assets/447391/54d00374-70d7-45f8-901a-610c035d6794)
![image](https://github.com/Banalian/ExtraLeaderboardPositions/assets/447391/756f0ff3-3155-41f5-b398-aa87718a630f)

2023-07-01 03:08 UTC, Banalian commented
Looks great ! I'll check out the PR code next week, and i'll integrate it and credit you in the next update, thanks for you work :D !

2023-07-01 03:09 UTC, Banalian commented
In the meantime, could you squash these commits into 1-3 commits to reduce the list please ? :p

2023-07-01 08:31 UTC, tboby commented
> In the meantime, could you squash these commits into 1-3 commits to reduce the list please ? :p

Done!

2023-07-01 19:55 UTC, Banalian requested changes
Looks great, thanks for the feature ! 
If i could do a bit of nitpick, do you think you could remove the lines that removes whitespaces/tabs ? I know my code is pretty inconsistent, so i'll instead do a commit focusing on removing those :p. If you can't, i'll still merge this, np !

2023-07-01 19:55 UTC, Banalian commented on Render/RenderSettings.as
> +
Nice addition, i'll probably reuse that for exisiting/future features that requires the API

2023-07-03 07:02 UTC, tboby commented
> Looks great, thanks for the feature ! If i could do a bit of nitpick, do you think you could remove the lines that removes whitespaces/tabs ? I know my code is pretty inconsistent, so i'll instead do a commit focusing on removing those :p. If you can't, i'll still merge this, np !

Done!

For future reference (partially to myself)

```
git rebase -i HEAD~2
<set commits as edit>
git reset HEAD^
<set editor to ignore whitespace>
<stage all changes>
git commit -m ""
git rebase --continue
```

2023-07-03 21:17 UTC, Banalian approved these changes

2023-07-03 21:18 UTC, Banalian commented
Thanks again for this feature ! It'll be included in the next version of the plugin which I should deploy this week !

2023-07-03 21:18 UTC, merged